version: '3.8'

services:
  backend:
    build: ./backend
    container_name: blog-backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=your_database_url_here
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: blog-frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres
    restart: always
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
